name = "aia-x402"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
# Set this to a Base mainnet USDC address you control
# wrangler secret put USDC_ADDRESS_BASE
# (do NOT commit the real address)

[[kv_namespaces]]
binding = "AIA_KV"
id = "bd4e22823cc5435da05a9f7baee186be"
