"""MoltJobs job fulfillment. When a bid is accepted, AIA produces a research
deliverable from the curated feed and submits via PATCH /v1/jobs/{id}/submit.

The deliverable is a markdown report synthesized from the latest curated
feed, focusing on the niche keywords the poster likely cares about.
"""
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from . import config
from . import moltjobs
from .net import patch


def get_bid_status(bid_id):
    """No public GET endpoint for individual bids. Use list_my_jobs() / events()."""
    return None


def list_my_jobs():
    """Return the jobs assigned to my agent."""
    if not config.MOLT_API_KEY:
        return []
    h = {"x-api-key": config.MOLT_API_KEY}
    me = moltjobs.get_me()
    agent_id = (me or {}).get("data", {}).get("id") or (me or {}).get("id")
    if not agent_id:
        return []
    data = moltjobs.get(f"{config.MOLT_API_BASE}/agents/{agent_id}/jobs", headers=h) if hasattr(moltjobs, "get") else None
    # Use raw urllib via net.get since moltjobs doesn't expose get()
    from .net import get
    data = get(f"{config.MOLT_API_BASE}/agents/{agent_id}/jobs", headers=h)
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        return data.get("data") or data.get("jobs") or []
    return []


def get_job(job_id):
    if not config.MOLT_API_KEY:
        return None
    h = {"x-api-key": config.MOLT_API_KEY}
    from .net import get
    data = get(f"{config.MOLT_API_BASE}/jobs/{job_id}", headers=h)
    if isinstance(data, dict) and "data" in data:
        return data["data"]
    return data


def get_job_events(job_id):
    if not config.MOLT_API_KEY:
        return []
    h = {"x-api-key": config.MOLT_API_KEY}
    from .net import get
    data = get(f"{config.MOLT_API_BASE}/jobs/{job_id}/events", headers=h)
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        return data.get("data") or data.get("events") or []
    return []


# -----------------------------------------------------------
# Deliverable synthesizer
# -----------------------------------------------------------

def _clean(title):
    return re.sub(r"\s+", " ", title or "").strip()


def synthesize_research_report(job, feed=None):
    """Build a markdown research brief from the current feed.
    Targets the job's title + description by extracting niche keywords.
    """
    feed = feed or json.loads(config.DATA_DIR.joinpath("feed.json").read_text(encoding="utf-8"))
    # job may be raw or wrapped envelope
    if isinstance(job, dict) and "data" in job and isinstance(job["data"], dict):
        job = job["data"]
    title = job.get("title", "Research task")
    desc = (job.get("description") or (job.get("inputData") or {}).get("description") or "").strip()
    industry = (job.get("inputData") or {}).get("industry") or ""

    tokens = set(re.findall(r"[a-z]{4,}", (title + " " + desc).lower()))
    # Ban obvious promo / seller tokens
    for bad in ("promote", "moltjobs", "newsletter", "tiktok", "twitter", "instagram"):
        tokens.discard(bad)

    # Score feed signals against the request tokens
    scored = []
    for s in feed.get("signals", []):
        text = (s.get("title", "") + " " + s.get("url", "")).lower()
        hits = sum(1 for t in tokens if t in text)
        # Niche keywords boost (any topic tag overlap)
        topic_match = any(t.replace("-","") in text for t in tokens)
        score = s.get("final_score", 0) + (hits * 200) + (300 if topic_match else 0)
        scored.append((score, s))
    scored.sort(key=lambda x: x[0], reverse=True)
    top = [s for _, s in scored[:20]]

    md_lines = [
        f"# Research Brief: {title}",
        "",
        f"_Generated by AIA — Autonomous Insight Agent on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
    ]
    if desc:
        md_lines += ["## Brief from requester", "", desc, ""]
    if industry:
        md_lines += [f"**Stated industry:** {industry}", ""]

    md_lines += [
        f"## Top 20 ranked signals (curated from 6 public sources)",
        "",
        "Each item is ranked by engagement × source weight × recency × topic match against your keywords.",
        "",
    ]
    for i, s in enumerate(top, 1):
        topics = ", ".join(s.get("topics") or []) or "-"
        md_lines += [
            f"{i}. [{_clean(s.get('title',''))}]({s.get('url','')})",
            f"   - source: `{s.get('source','')}`  score: {round(s.get('final_score',0),1)}  topics: {topics}",
            "",
        ]

    md_lines += [
        "## Methodology",
        "",
        "AIA collected 100+ raw items from 6 public sources (Hacker News, GitHub trending, V2EX, dev.to, Lobsters, HN Algolia), deduplicated, ranked, and filtered for keyword match. Every cited item links to its source. The same signal stream is published free at https://razel369.github.io/aia/ and as a paid x402 API at https://aia-x402.rmalka06.workers.dev (USDC on Base, $0.01/call).",
        "",
        "— AIA",
    ]
    return "\n".join(md_lines)


def synthesize_short_report(job, feed=None):
    """Shorter 5-bullet digest suitable for 'find a product' style jobs."""
    feed = feed or json.loads(config.DATA_DIR.joinpath("feed.json").read_text(encoding="utf-8"))
    if isinstance(job, dict) and "data" in job and isinstance(job["data"], dict):
        job = job["data"]
    title = job.get("title", "")
    desc = (job.get("description") or (job.get("inputData") or {}).get("description") or "")
    industry = (job.get("inputData") or {}).get("industry") or "Computer"
    tokens = set(re.findall(r"[a-z]{4,}", (title + " " + desc + " " + industry).lower()))
    for bad in ("promote","moltjobs","newsletter","tiktok","twitter","instagram"):
        tokens.discard(bad)
    scored = []
    for s in feed.get("signals", []):
        text = (s.get("title","") + " " + s.get("url","")).lower()
        hits = sum(1 for t in tokens if t in text)
        score = s.get("final_score", 0) + (hits*200)
        scored.append((score, s))
    scored.sort(key=lambda x: x[0], reverse=True)
    picks = [s for _, s in scored[:5]]
    lines = [f"# {title}", "", f"_Industry: {industry}_", "", "## Top 5 picks", ""]
    for i, s in enumerate(picks, 1):
        lines.append(f"{i}. **{_clean(s.get('title',''))[:120]}**")
        lines.append(f"   {s.get('url','')}")
        lines.append(f"   ({s.get('source','')}, score {round(s.get('final_score',0),1)})")
        lines.append("")
    return "\n".join(lines)


def submit(job_id, deliverable_text, deliverable_kind="report"):
    """PATCH /v1/jobs/{id}/submit with the deliverable as outputData."""
    if not config.MOLT_API_KEY:
        return None
    h = {"x-api-key": config.MOLT_API_KEY}
    body = {
        "outputData": {
            "kind": deliverable_kind,
            "format": "markdown",
            "text": deliverable_text,
            "deliveredBy": "AIA — Autonomous Insight Agent",
            "deliveredAt": datetime.now(timezone.utc).isoformat(),
            "freePublicDashboard": "https://razel369.github.io/aia/",
            "paidApi": "https://aia-x402.rmalka06.workers.dev",
            "agentId": "boyyy",
        }
    }
    from .net import patch
    return patch(f"{config.MOLT_API_BASE}/jobs/{job_id}/submit", body, headers=h)


# -----------------------------------------------------------
# Heartbeat (required for agent visibility)
# -----------------------------------------------------------

def heartbeat(status_text):
    if not config.MOLT_API_KEY:
        return None
    h = {"x-api-key": config.MOLT_API_KEY}
    from .net import post
    me = moltjobs.get_me()
    agent_id = (me or {}).get("data", {}).get("id") or (me or {}).get("id")
    if not agent_id:
        return None
    return post(f"{config.MOLT_API_BASE}/agents/{agent_id}/heartbeat",
                {"status": status_text}, headers=h)
